import type { Metadata } from "next";
import { Nunito } from "next/font/google";

import { Header } from "../../shared/components/shared";

const nunito = Nunito({ 
  subsets: ['cyrillic'],
  variable: '--font-nunito',
  weight: ['400', '500', '600', '700', '800', '900'],
});

export const metadata: Metadata = {
  title: "Next Pizza | Главная",
  description: "Generated by create next app",
};

export default function HomeLayout({
  children,
  modal,
}: Readonly<{
  children: React.ReactNode;
  modal: React.ReactNode;
}>) {
  return (
        <main className="min-h-screen">
          <Header />
          {children}
          {modal}
        </main>
  );
}
